//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public Departments()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public System.Guid Department_Id { get; set; }
        public string Department_Name { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
