//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Email = new HashSet<Email>();
            this.Phone = new HashSet<Phone>();
            this.Departments = new HashSet<Departments>();
        }
    
        public System.Guid Employees_Id { get; set; }
        public string Employees_FIO { get; set; }
    
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<Phone> Phone { get; set; }
        public virtual ICollection<Departments> Departments { get; set; }
    }
}
