//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form_Employees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public System.Guid Phone_Id { get; set; }
        public string Phone_Name { get; set; }
        public System.Guid TypePhone_Id { get; set; }
        public System.Guid Employees_Id { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual TypePhone TypePhone { get; set; }
    }
}
